
import javax.swing.JFrame;
import java.awt.Container;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.event.MouseMotionListener;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JPanel;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author davidalba
 */
public class InterfaceForm extends javax.swing.JFrame {

    
    /**
     * Creates new form InterfaceForm
     */
    public InterfaceForm() {
        initComponents();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        B_START = new javax.swing.JButton();
        B_HELP = new javax.swing.JButton();
        B_QUIT = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 0));
        jLabel1.setText("MENU");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(250, 10, 40, 16);

        B_START.setBackground(new java.awt.Color(204, 204, 0));
        B_START.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        B_START.setText("START");
        B_START.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_STARTActionPerformed(evt);
            }
        });
        getContentPane().add(B_START);
        B_START.setBounds(20, 40, 91, 29);

        B_HELP.setBackground(new java.awt.Color(204, 204, 0));
        B_HELP.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        B_HELP.setText("HELP");
        B_HELP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_HELPActionPerformed(evt);
            }
        });
        getContentPane().add(B_HELP);
        B_HELP.setBounds(20, 80, 90, 29);

        B_QUIT.setBackground(new java.awt.Color(204, 204, 0));
        B_QUIT.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        B_QUIT.setText("QUIT");
        B_QUIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_QUITActionPerformed(evt);
            }
        });
        getContentPane().add(B_QUIT);
        B_QUIT.setBounds(20, 120, 90, 29);

        jLabel2.setIcon(new javax.swing.ImageIcon("/Users/davidalba/SDD-Project/images/background.gif")); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 550, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B_STARTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_STARTActionPerformed
        try {
            Main game = new Main();
            game.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            game.setResizable(false);
            game.setVisible(true);
            //GameStarted gs = new GameStarted();
            //gs.setSize(500, 400);
            //gs.setLocation(300, 100); //400, 200
            //gs.setResizable(false);
            //gs.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(InterfaceForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_B_STARTActionPerformed

    private void B_HELPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_HELPActionPerformed
         HelpInterface h = new HelpInterface();
        h.setSize(500, 400);
        h.setLocation(300, 100); //400, 200
        h.setResizable(false);
        h.setVisible(true);
    }//GEN-LAST:event_B_HELPActionPerformed

    private void B_QUITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_QUITActionPerformed
        System.exit(0);
    }//GEN-LAST:event_B_QUITActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_HELP;
    private javax.swing.JButton B_QUIT;
    private javax.swing.JButton B_START;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
